In [1]:
import numpy as np
import robot

In [2]:
r = robot.Robot(
    max_motor_speed=1.0,
    wheelbase=[0.2],
    lenght=[0.14],
    engine_cutoff=0.1,
    rotation=0.0,
    sensor_width=[0.067],
    sensor_n=8,
    sensor_noise=0.1,
    min_speed=0.1,
    position=[0.0, 0.0]
)

In [3]:
r.move(np.array([0.0]), np.array([1.0]), 0.1)

[[0.05]
 [0.  ]]
[[0. 0.]]


ValueError: non-broadcastable output operand with shape (1,2) doesn't match the broadcast shape (2,2)

In [4]:
a = np.array([[2, 1], [3, 7]])
b = np.array([[1, 2], [3, 4]])
a+b

array([[ 3,  3],
       [ 6, 11]])