In [1]:
import neural_network as nn
import robot_controller as rc
import numpy as np

In [2]:
batch_n = 7
layers = np.array([6, 5, 4])
parameters = np.random.randn(batch_n, 59)

In [3]:
net = nn.NeuralNetwork(layers, parameters)

In [4]:
net.forward(np.random.randn(batch_n, 6))

array([[-0.99005328,  0.9936372 , -0.3583943 , -0.23976913],
       [-0.28114511,  0.97408603,  0.99943764, -0.94344985],
       [ 0.71459407, -0.94303979,  0.80462697, -0.99952523],
       [ 0.42601779,  0.85956887, -0.99416093,  0.98578827],
       [ 0.98436736, -0.95864562, -0.9707491 , -0.91036828],
       [ 0.9985253 ,  0.06473048,  0.74134145, -0.96676506],
       [ 0.99912094, -0.99849675,  0.81657011,  0.21147498]])

In [5]:
controller = rc.RobotController(layers, parameters, 2)

In [6]:
controller.get_motors(np.random.randn(batch_n, 4))

array([[-0.4832137 ,  0.59919236],
       [-0.97650831,  0.91316882],
       [ 0.94171193, -0.99720985],
       [-0.07307307, -0.98753392],
       [ 0.83266534, -0.66398386],
       [ 0.9950644 ,  0.07447478],
       [ 0.76111576, -0.97618398]])

In [23]:
sensor_positions = np.array([0.15, 0]) + np.array(np.meshgrid(np.linspace(-0.03, 0.0, 3), np.linspace(-0.04, 0.04, 8))).T.reshape(-1, 2)

In [24]:
sensor_positions

array([[ 0.12      , -0.04      ],
       [ 0.12      , -0.02857143],
       [ 0.12      , -0.01714286],
       [ 0.12      , -0.00571429],
       [ 0.12      ,  0.00571429],
       [ 0.12      ,  0.01714286],
       [ 0.12      ,  0.02857143],
       [ 0.12      ,  0.04      ],
       [ 0.135     , -0.04      ],
       [ 0.135     , -0.02857143],
       [ 0.135     , -0.01714286],
       [ 0.135     , -0.00571429],
       [ 0.135     ,  0.00571429],
       [ 0.135     ,  0.01714286],
       [ 0.135     ,  0.02857143],
       [ 0.135     ,  0.04      ],
       [ 0.15      , -0.04      ],
       [ 0.15      , -0.02857143],
       [ 0.15      , -0.01714286],
       [ 0.15      , -0.00571429],
       [ 0.15      ,  0.00571429],
       [ 0.15      ,  0.01714286],
       [ 0.15      ,  0.02857143],
       [ 0.15      ,  0.04      ]])