In [1]:
import numpy as np

In [26]:
batch_n = 5
input_len = 3
output_len = 2

In [70]:
x = np.random.randn(batch_n, input_len)
W = np.random.randn(batch_n, output_len, input_len)
b = np.random.randn(batch_n, output_len)

In [71]:
x, W

(array([[-0.3996095 ,  0.84136726,  0.39653885],
        [-1.05589789,  0.03608312,  0.44058745],
        [ 0.21133436,  0.48894449, -0.05501375],
        [-0.98412926,  0.59701478,  0.41088003],
        [ 0.50863574, -0.02649438, -0.01384508]]),
 array([[[ 0.38158432, -0.25309675, -0.0478214 ],
         [ 0.01177225, -1.32855138,  1.81299305]],
 
        [[ 2.07452898,  0.6602195 ,  0.49690708],
         [-1.38427762,  0.54021537, -0.73518451]],
 
        [[ 0.00467902,  0.17662725,  0.41614179],
         [-0.71114308,  0.38393304,  1.21085359]],
 
        [[ 0.65005519,  0.74822558, -0.35179889],
         [-1.78507785,  0.71289528,  0.24410147]],
 
        [[-1.92797717,  1.07013627, -0.12249036],
         [ 0.95816069,  0.06591349, -0.60346898]]]))

In [74]:
np.einsum('bnm, bm -> bn', W, x) + b

array([[ 0.71283249, -2.20993865],
       [-2.53759317, -0.01323719],
       [ 0.11734463,  1.90196011],
       [-1.95896599,  2.25495644],
       [-2.28315892,  2.3214353 ]])